"""Build the browser data file from the released JSON; never change measurements."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    board = json.loads((ROOT / 'leaderboard/leaderboard.json').read_text())
    payload = '// Generated by tools/build_site.py.\nwindow.KVA_LEADERBOARD = '
    payload += json.dumps(board, ensure_ascii=False, separators=(',', ':'), allow_nan=False) + ';\n'
    target = ROOT / 'leaderboard/leaderboard_data.js'
    if args.check:
        if not target.exists() or target.read_text() != payload:
            raise SystemExit('Browser data is stale. Run python tools/build_site.py')
        print('PASS: browser data exactly matches the released JSON.')
    else:
        target.write_text(payload, encoding='utf-8')
        print('Built leaderboard/leaderboard_data.js')


if __name__ == '__main__':
    main()
